# Лабораторная работа 3. Вариант 1. Группа 343

In [1]:
import numpy as np
from numpy import linalg as LA

A = np.array([[-0.81417, -0.01937, 0.41372 ],
              [-0.01937,  0.54414,  0.00590],
              [0.41372, 0.00590, -0.81445]])
print('A =\n', A)
epsilon_1 = 0.001
epsilon_2 = 0.000001


def find_normed_vector(v):
    return v / LA.norm(v, 2)


y0 = np.array([[0.1, 0.1, 0.1]]).T
print('Y0 =\n', y0)


def find_yk(A, k):
    if k < 0:
            raise ValueError('k can not be negative')
    if k == 0:
        return y0
    return np.dot(A, find_yk(A, k - 1))

A =
 [[-0.81417 -0.01937  0.41372]
 [-0.01937  0.54414  0.0059 ]
 [ 0.41372  0.0059  -0.81445]]
Y0 =
 [[0.1]
 [0.1]
 [0.1]]


### 1) Найти степенным методом с точностью $\varepsilon=0.001$ максимальное по модулю собственное число $\lambda_1$ матрицы $A$ и соответствующий ему собственный вектор $x^{(1)}$, так чтобы $\|x^{(1)}\|_2=1$.

In [2]:
def find_eigenvalue_and_y_power(A, epsilon):
    def find_eigenvalue_and_y_rec(k, prev_lambdas = None):
        yk = find_yk(A, k)
        yk1 = find_yk(A, k + 1)
        lambdas = yk1 / yk
        if prev_lambdas is not None:
            yk_prev = find_yk(A, k - 1)
            max_lambda = np.amax(lambdas)
            error = LA.norm(np.dot(A, yk_prev) - np.dot(max_lambda, yk_prev), 2) / LA.norm(yk_prev, 2)
            if error <= epsilon:
                return (max_lambda, yk, k)

        return find_eigenvalue_and_y_rec(k + 1, lambdas)
    
    return find_eigenvalue_and_y_rec(0)

    
(power_eigenvalue, power_y, power_iterations) = find_eigenvalue_and_y_power(A, epsilon_1)

normed_y = find_normed_vector(power_y)
print('Максимальное по модулю с.ч.:\n', power_eigenvalue)
print('Собственный вектор:\n', normed_y)
print('Число итераций: ', power_iterations)

Максимальное по модулю с.ч.:
 -1.228206052434601
Собственный вектор:
 [[-0.7070352 ]
 [-0.00998411]
 [ 0.70710787]]
Число итераций:  17


### 2) Найти методом скалярных произведений с точностью $\varepsilon^2=0.000001$ максимальное по модулю собственное число матрицы $\lambda_1$. Сравнить требуемое количество итераций с п.1.


In [3]:
def find_eigenvalue_scalar(A, epsilon):
    def find_eigenvalue_rec(k, prev_lambdas = None):
        yk = find_yk(A, k)
        yk1 = find_yk(A, k + 1)
        lambdas = (yk1 * yk) / (yk * yk)
        if prev_lambdas is not None:
            yk_prev = find_yk(A, k - 1)
            max_lambda = np.amax(lambdas)
            error = LA.norm(np.dot(A, yk_prev) - np.dot(max_lambda, yk_prev), 2) / LA.norm(yk_prev, 2)
            if error <= epsilon:
                return (max_lambda, k)

        return find_eigenvalue_rec(k + 1, lambdas)
    
    return find_eigenvalue_rec(0)

(scalar_eigenvalue, scalar_iterations) = find_eigenvalue_scalar(A, epsilon_2)
print('Максимальное по модулю с.ч.:\n', scalar_eigenvalue)
print('Число итераций: ', scalar_iterations)

Максимальное по модулю с.ч.:
 -1.228210145719265
Число итераций:  25


### Ожидается, что число итераций будет схожим, т.к. в первом случае использовали $\varepsilon$, а во втором $-$ $\varepsilon^2$

In [4]:
print('Число итераций в п.1: ', power_iterations)
print('Число итераций в п.2: ', scalar_iterations)

Число итераций в п.1:  17
Число итераций в п.2:  25
