In [167]:
import numpy as np
from numpy import linalg as LA
from IPython.display import display, Math, Latex


def find_inverse(A):
    shape = A.shape
    if len(shape) != 2 or shape[0] != shape[1]:
        raise ValueError('A is not square 2d matrix')

    n = len(A)

    B = np.eye(n)

    # Elimination
    for i in range(n):
        if A[i][i] == 0:
            raise ValueError('Pivot is zero applying Gauss Jordan elimination')

        for j in range(n):
            if i != j:
                ratio = A[j, i] / A[i, i]

                for k in range(n):
                    A[j][k] = A[j][k] - ratio * A[i][k]
                    B[j][k] = B[j][k] - ratio * B[i][k]

    # Normalization
    for i in range(n):
        B[i] /= A[i][i]

    return B



# P.94 V.1
A = np.array([[3.278164, 1.046583, -2.06459],
              [1.046583,  2.975937,  0.934251],
              [-1.378574, 0.934251, 4.836173]])

b = np.array([[-0.527466],
              [2.526877],
              [5.165441]])

accuracy = 9

Дана линейная система Ax=b

In [168]:
print('A =\n', A)
print('b =\n', b)

A =
 [[ 3.278164  1.046583 -2.06459 ]
 [ 1.046583  2.975937  0.934251]
 [-1.378574  0.934251  4.836173]]
b =
 [[-0.527466]
 [ 2.526877]
 [ 5.165441]]


In [169]:
display(Latex('1) Найти решение $x^∗$ методом Гаусса.'))

<IPython.core.display.Latex object>

In [170]:
def find_solution_gauss(A, b, use_pivoting=False):
    n = len(A)
    if b.size != n:
        raise ValueError('Incompatible sizes of A and b')

    for i in range(n - 1):
        if use_pivoting:
            pivot_index = abs(A[i:, i]).argmax() + i
            if A[pivot_index, i] == 0:
                raise ValueError('A is singular')

            if pivot_index != i:
                A[[i, pivot_index]] = A[[pivot_index, i]]
                b[[i, pivot_index]] = b[[pivot_index, i]]
        else:
            if A[i, i] == 0:
                raise ValueError('Pivot is zero')

        for j in range(i + 1, n):
            ratio = A[j, i] / A[i, i]
            A[j, i:] -= ratio * A[i, i:]
            b[j] -= ratio * b[i]

    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]

    return x

x_sln = find_solution_gauss(np.copy(A), b)
print(x_sln)

[0.44116647 0.33976985 1.12820433]


In [171]:
display(Latex('2) Преобразовать исходную систему к системе вида $x = H_Dx+g_D$ , где $H_D = E − D^{−1}A$, $g_D = D^{−1}b$. Здесь D — диагональная матрица, у которой на диагонали находятся диагональные элементы матрицы A. Вычислить $\|H_D\|_\infty$.'))

<IPython.core.display.Latex object>

In [172]:
D = np.diag(np.diag(np.copy(A)))
print('D =\n', D)
Hd = np.eye(len(A)) - LA.inv(np.copy(D)).dot(A).round(accuracy)
print('\nHd =\n', Hd)
gd = LA.inv(np.copy(A)).dot(b).round(accuracy)
print('\ngd =\n', gd)
hd_norm = LA.norm(Hd, np.inf)
print('\n||Hd|| =\n', hd_norm)

D =
 [[3.278164 0.       0.      ]
 [0.       2.975937 0.      ]
 [0.       0.       4.836173]]

Hd =
 [[ 0.         -0.31925889  0.62980071]
 [-0.35168184  0.         -0.31393507]
 [ 0.28505473 -0.19317981  0.        ]]

gd =
 [[-0.02759516]
 [ 0.73239185]
 [ 0.58293095]]

||Hd|| =
 0.9490595960000001


In [173]:
display(Latex('3) Вычислить априорную оценку погрешности $\|x^{(7)} − x^*\|_\infty$.'))

<IPython.core.display.Latex object>

In [174]:
def count_aprior_error(H, g, x0, k):
    return LA.norm(H, np.inf) ** k * LA.norm(x0, np.inf) + (LA.norm(H, np.inf) ** k / (1 - LA.norm(H, np.inf))) * LA.norm(g, np.inf)
    
aprior_error = count_aprior_error(Hd, gd, np.zeros((len(Hd), 1)), 7)
print('Априорная оценка: ||x_k - x*|| <= ', aprior_error)

Априорная оценка: ||x_k - x*|| <=  9.970926449297338


In [175]:
display(Latex('4) Вычислить приближение $x^{(7)}$ методом простой итерации. Вывести его фактическую погрешность, апостериорную оценку, априорную оценку. Уточнить последнее приближение по Люстернику. Вывести его фактическую погрешность.'))

<IPython.core.display.Latex object>

In [176]:
def find_solution_simple_iteration(H, g, k):
    if k < 0:
        raise ValueError('k can not be negative')
    if k == 0:
        return np.zeros((len(H), 1))
    return H.dot(find_solution_simple_iteration(H, g, k - 1)) + g


def count_aposterior_error(H, xk, xk1):
    return (LA.norm(H, np.inf) / (1 - LA.norm(H, np.inf))) * LA.norm(xk - xk1, np.inf)

x_6 = find_solution_simple_iteration(Hd, gd, 6)
x_7 = find_solution_simple_iteration(Hd, gd, 7)
aposterior_error = count_aposterior_error(Hd, x_7, x_6)
print('x_7 =\n', x_7)
print('Апостериорная оценка: ||x_7 - x*|| <= ', aposterior_error)
print('Априорная оценка: ||x_k - x*|| <= ', aprior_error)
print('||x_7 - x*|| = ', LA.norm(x_7 - x_sln, np.inf))

x_7 =
 [[0.12271025]
 [0.52982163]
 [0.51409604]]
Апостериорная оценка: ||x_7 - x*|| <=  0.09291379686341547
Априорная оценка: ||x_k - x*|| <=  9.970926449297338
||x_7 - x*|| =  1.541009890416078


In [35]:
display(Latex('5) Вычислить приближение $x^{(7)}$ к решению системы $x = H_Dx + g_D$ методом Зейделя. Вывести его фактическую погрешность. Сравнить с решением, полученным методом простой итерации.'))

<IPython.core.display.Latex object>

In [38]:
display(Latex('6) При выполнении задания в математическом пакете определить спектральный радиус матрицы перехода, если рассматривать метод Зейделя как метод простой итерации.'))

<IPython.core.display.Latex object>

In [36]:
display(Latex('7) Вычислить приближение $x^{(7)}$ методом верхней релаксации.'))

<IPython.core.display.Latex object>

In [37]:
display(Latex('Сравнить фактические погрешности $x^{(7)}$, полученного различными методами.'))

<IPython.core.display.Latex object>